library(shiny)
library(dipsaus)
library(shinydashboard)
library(jsonlite)
library(devtools)
library(distRcpp)
library(shinyFeedback)
library(shinyjs)
library(bslib)
library(bsicons)
library(shinyBS)
library(RSQLite)
library(DBI)
library(plotly)
library(RColorBrewer)
library(viridisLite)
library(patchwork)
library(colorspace)

source("R/clustering/normalization_methods.R")
source("data/database_functions_v4.r")
source("R/clustering/hierarchical_clustering.R")
source("R/clustering/prepare_data.R")
source("R/visualization/heatmap_final.R")
source("R/visualization/dendrogram_data_functions.R") 
source("R/visualization/final_tree_functions.R") 
source("R/visualization/dendrogram_plotter.R") 
source("R/visualization/graphics_panel.R")

source("R/utils/na_preprocessing.R")
source("R/utils/presets.R")
source("R/utils/pdf_export.R")

source("app/ui.R")
source("app/server.R")
shinyApp(ui = ui, server = server)



